# Generated by Django 5.1.7 on 2025-03-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0006_remove_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(choices=[('admin', 'Admin'), ('engenharia', 'Engenharia'), ('vendedor', 'Vendedor'), ('compras', 'Compras')], max_length=20),
        ),
    ]
